### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/funcionario/10 HTTP/1.1

### Verbo POST – adicionar
POST http://localhost:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome": "admin",
    "matricula": "admin",
    "cpf": "00123456789",
    "telefone": "001",
    "grupo": 1,
    "senha": "admin",
    "email": "admin@provedor.net"
}

### Verbo PUT – atualiza
PUT http://localhost:8000/funcionario/1 HTTP/1.1
content-type: application/json

{
    "nome": "henrique agostinetto piva atualizado",
    "matricula": "00000000001",
    "cpf": "01349677982",
    "telefone": "240028922",
    "grupo": 1,
    "senha": "Opala1977",
    "email": "henrique@provedor.net"
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/funcionario/4 HTTP/1.1

### Login para obter access e refresh tokens
POST http://127.0.0.1:8000/auth/login HTTP/1.1
content-type: application/json

{
"cpf" : "01349677981",
"senha" : "opaalao1977"
}

### token gerado
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODc2NTQzMjEwMiIsImlkIjoxLCJncnVwbyI6MSwiZXhwIjoxNzc0OTM0OTA0LCJ0eXBlIjoiYWNjZXNzIn0.113xLdd6tBCbO4BCSm4be9HBLcO7k1icP2t5Kjxld-o
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODc2NTQzMjEwMiIsImlkIjoxLCJncnVwbyI6MSwiZXhwIjoxNzc1NTMyOTMxLCJ0eXBlIjoicmVmcmVzaCJ9.VPaIWzk15Ev0ITOa36jVohCK69qgN6lMsHrPrAH795A
### testar access token para acessar endpoint protegido
GET http://127.0.0.1:8000/auth/me HTTP/1.1
Authorization: Bearer {{access_token}}

### Usar refresh token para obter novos tokens
POST http://localhost:8000/auth/refresh
Content-Type: application/json

{
    "refresh_token": "{{refresh_token}}"
}

# token
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODc2NTQzMjEwMiIsImlkIjoxLCJncnVwbyI6MSwiZXhwIjoxNzc0OTM0OTA0LCJ0eXBlIjoiYWNjZXNzIn0.113xLdd6tBCbO4BCSm4be9HBLcO7k1icP2t5Kjxld-o

### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{access_token}}

### Verbo GET – listar um
GET http://localhost:8000/funcionario/2 HTTP/1.1
Authorization: Bearer {{access_token}}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}
{
"nome" : "Luciano Coelho atualizado"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
Authorization: Bearer {{access_token}}

# Henrique Agostinetto Piva